In [1]:
import numpy as np

In [14]:
arr = np.array([33,44,5,55,13,553,667,11,3,7,88], np.int64)

print(type(arr))

<class 'numpy.ndarray'>


In [15]:
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.strides)
print(arr.itemsize)
print(arr.nbytes)

[ 33  44   5  55  13 553 667  11   3   7  88]
1
(11,)
11
int64
(8,)
8
88


In [19]:
twoL = [[1,2,4],[4,5,6],[7,8,9]]

twoD = np.array(twoL)


In [20]:
print(twoD)
print(twoD.ndim)
print(twoD.shape)
print(twoD.size)
print(twoD.dtype)
print(twoD.strides)
print(twoD.itemsize)
print(twoD.nbytes)

[[1 2 4]
 [4 5 6]
 [7 8 9]]
2
(3, 3)
9
int32
(12, 4)
4
36


In [23]:
arr = np.zeros((4,5))
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [25]:
arr2 = np.ones((3,6))
arr2

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [27]:
arr3 = np.full(7,54) #create a 1-d array and fill 54
arr3

array([54, 54, 54, 54, 54, 54, 54])

In [29]:
arr4 = np.full((3,4),78) #create a 2-d array and fill 78
arr4

array([[78, 78, 78, 78],
       [78, 78, 78, 78],
       [78, 78, 78, 78]])